### PR TITLE
Documentation update + node-pre-gyp fix

### PR DESCRIPTION
**Pull request by gbertoncelli**
Fixes the `node-pre-gyp` problem #27

### CODE REVIEW

**Review by artsrun-g — APPROVED** [review]

**Comment by andrewgierens** [comment]
Any chance this can be merged?

**Comment by samarthsikotara** [comment]
@artsrun-g when will you merge? please let us know? eagerly waiting 

Thanks!

**Comment by artsrun-g** [comment]
@samarthsikotara Someone with write access will need to merge it.

**Review by artsrun-g — APPROVED** [review]

**Comment by gbertoncelli** [comment]
@netPark-Developer

**Review by atesztoth — APPROVED** [review]

**Review by zkrige — APPROVED** [review]

**Pull request merged**
